import { PrismaClient } from '@prisma/client';
import bcrypt from 'bcryptjs';

const prisma = new PrismaClient();

const recipes = [
  // 中餐 - 现有2道
  {
    title: '宫保鸡丁',
    description: '经典川菜，鸡肉鲜嫩，花生酥脆，酸甜微辣',
    servings: 4,
    cookTime: 25,
    imageUrl: 'https://images.unsplash.com/photo-1603073163308-9c4f7d4e0c8e?w=800',
    tags: '中餐,川菜,快手,晚餐',
    ingredients: JSON.stringify([
      { name: '鸡胸肉', amount: 300, unit: 'g' },
      { name: '花生米', amount: 80, unit: 'g' },
      { name: '干辣椒', amount: 10, unit: '个' },
      { name: '葱', amount: 2, unit: '根' },
      { name: '姜', amount: 1, unit: '块' },
      { name: '蒜', amount: 3, unit: '瓣' },
      { name: '生抽', amount: 2, unit: '勺' },
      { name: '醋', amount: 1, unit: '勺' },
      { name: '糖', amount: 1, unit: '勺' },
      { name: '淀粉', amount: 1, unit: '勺' },
    ]),
    steps: JSON.stringify([
      '鸡胸肉切丁，加生抽、淀粉腌制15分钟',
      '花生米炸至金黄捞出',
      '热油爆香干辣椒、葱姜蒜',
      '下鸡丁快速翻炒至变色',
      '加入生抽、醋、糖调味',
      '最后加入花生米翻炒均匀即可',
    ]),
    source: 'seed',
  },
  {
    title: '番茄炒蛋',
    description: '国民家常菜，酸甜开胃，营养丰富',
    servings: 2,
    cookTime: 10,
    imageUrl: 'https://images.unsplash.com/photo-1608897013039-887f21d8c804?w=800',
    tags: '中餐,家常,快手,早餐',
    ingredients: JSON.stringify([
      { name: '番茄', amount: 3, unit: '个' },
      { name: '鸡蛋', amount: 4, unit: '个' },
      { name: '葱', amount: 1, unit: '根' },
      { name: '盐', amount: 1, unit: '茶勺' },
      { name: '糖', amount: 0.5, unit: '勺' },
    ]),
    steps: JSON.stringify([
      '番茄切块，鸡蛋打散加少许盐',
      '热油炒鸡蛋至凝固盛出',
      '锅中加油炒番茄至出汁',
      '加盐和糖调味',
      '倒入鸡蛋翻炒均匀',
      '撒葱花出锅',
    ]),
    source: 'seed',
  },
  // 中餐 - 补充8道
  {
    title: '麻婆豆腐',
    description: '经典川菜，麻辣鲜香，豆腐嫩滑',
    servings: 3,
    cookTime: 20,
    imageUrl: 'https://images.unsplash.com/photo-1633180897-c9e5e4e1e3e5?w=800',
    tags: '中餐,川菜,素食,晚餐',
    ingredients: JSON.stringify([
      { name: '嫩豆腐', amount: 400, unit: 'g' },
      { name: '猪肉末', amount: 100, unit: 'g' },
      { name: '豆瓣酱', amount: 2, unit: '勺' },
      { name: '花椒粉', amount: 1, unit: '茶勺' },
      { name: '葱姜蒜', amount: 50, unit: 'g' },
      { name: '生抽', amount: 1, unit: '勺' },
      { name: '淀粉水', amount: 3, unit: '勺' },
    ]),
    steps: JSON.stringify([
      '豆腐切块，焯水备用',
      '热油炒肉末至变色',
      '加豆瓣酱炒出红油',
      '加葱姜蒜爆香',
      '倒入豆腐和适量水煮3分钟',
      '加生抽调味，淀粉水勾芡',
      '撒花椒粉出锅',
    ]),
    source: 'seed',
  },
  {
    title: '糖醋里脊',
    description: '酸甜可口，外酥里嫩，老少皆宜',
    servings: 3,
    cookTime: 30,
    imageUrl: 'https://images.unsplash.com/photo-1626804475297-41608ea09aeb?w=800',
    tags: '中餐,家常,炸物,晚餐',
    ingredients: JSON.stringify([
      { name: '猪里脊肉', amount: 300, unit: 'g' },
      { name: '鸡蛋', amount: 1, unit: '个' },
      { name: '淀粉', amount: 100, unit: 'g' },
      { name: '番茄酱', amount: 3, unit: '勺' },
      { name: '白醋', amount: 2, unit: '勺' },
      { name: '糖', amount: 3, unit: '勺' },
      { name: '盐', amount: 0.5, unit: '茶勺' },
    ]),
    steps: JSON.stringify([
      '里脊肉切条，加盐、鸡蛋腌制',
      '裹上淀粉，油炸至金黄',
      '锅中加番茄酱、醋、糖、水煮开',
      '倒入炸好的肉条快速翻炒',
      '收汁出锅',
    ]),
    source: 'seed',
  },
  {
    title: '红烧肉',
    description: '肥而不腻，色泽红亮，入口即化',
    servings: 4,
    cookTime: 90,
    imageUrl: 'https://images.unsplash.com/photo-1626804475297-41608ea09aeb?w=800',
    tags: '中餐,家常,炖菜,晚餐',
    ingredients: JSON.stringify([
      { name: '五花肉', amount: 500, unit: 'g' },
      { name: '冰糖', amount: 30, unit: 'g' },
      { name: '生抽', amount: 3, unit: '勺' },
      { name: '老抽', amount: 1, unit: '勺' },
      { name: '料酒', amount: 2, unit: '勺' },
      { name: '葱姜', amount: 50, unit: 'g' },
      { name: '八角', amount: 2, unit: '个' },
    ]),
    steps: JSON.stringify([
      '五花肉切块，焯水去血沫',
      '锅中炒冰糖至焦糖色',
      '下肉块翻炒上色',
      '加料酒、生抽、老抽、葱姜、八角',
      '加水没过肉，大火烧开转小火炖1小时',
      '大火收汁即可',
    ]),
    source: 'seed',
  },
  {
    title: '蒜蓉西兰花',
    description: '清淡健康，蒜香浓郁，营养丰富',
    servings: 2,
    cookTime: 10,
    imageUrl: 'https://images.unsplash.com/photo-1628773822503-930a7eaecf80?w=800',
    tags: '中餐,素食,快手,健康',
    ingredients: JSON.stringify([
      { name: '西兰花', amount: 300, unit: 'g' },
      { name: '蒜', amount: 5, unit: '瓣' },
      { name: '盐', amount: 1, unit: '茶勺' },
      { name: '蚝油', amount: 1, unit: '勺' },
      { name: '食用油', amount: 2, unit: '勺' },
    ]),
    steps: JSON.stringify([
      '西兰花切小朵，焯水1分钟',
      '蒜切末',
      '热油爆香蒜末',
      '倒入西兰花翻炒',
      '加盐和蚝油调味',
      '翻炒均匀出锅',
    ]),
    source: 'seed',
  },
  {
    title: '紫菜蛋花汤',
    description: '清淡鲜美，简单快手，营养补碘',
    servings: 2,
    cookTime: 5,
    imageUrl: 'https://images.unsplash.com/photo-1547592166-23ac45744acd?w=800',
    tags: '中餐,汤,快手,早餐',
    ingredients: JSON.stringify([
      { name: '紫菜', amount: 10, unit: 'g' },
      { name: '鸡蛋', amount: 2, unit: '个' },
      { name: '葱花', amount: 10, unit: 'g' },
      { name: '盐', amount: 1, unit: '茶勺' },
      { name: '香油', amount: 0.5, unit: '勺' },
    ]),
    steps: JSON.stringify([
      '紫菜撕碎，鸡蛋打散',
      '锅中烧开水',
      '放入紫菜煮1分钟',
      '倒入蛋液搅拌成蛋花',
      '加盐调味',
      '撒葱花，淋香油出锅',
    ]),
    source: 'seed',
  },
  {
    title: '蛋炒饭',
    description: '粒粒分明，蛋香浓郁，简单美味',
    servings: 1,
    cookTime: 10,
    imageUrl: 'https://images.unsplash.com/photo-1603133872878-684f208fb84b?w=800',
    tags: '中餐,主食,快手,午餐',
    ingredients: JSON.stringify([
      { name: '米饭', amount: 300, unit: 'g' },
      { name: '鸡蛋', amount: 2, unit: '个' },
      { name: '葱花', amount: 20, unit: 'g' },
      { name: '盐', amount: 1, unit: '茶勺' },
      { name: '生抽', amount: 1, unit: '勺' },
      { name: '食用油', amount: 3, unit: '勺' },
    ]),
    steps: JSON.stringify([
      '鸡蛋打散',
      '热油炒鸡蛋至凝固盛出',
      '锅中加油，倒入米饭炒散',
      '加入鸡蛋翻炒均匀',
      '加盐和生抽调味',
      '撒葱花出锅',
    ]),
    source: 'seed',
  },
  {
    title: '凉拌黄瓜',
    description: '清爽开胃，酸辣可口，夏日必备',
    servings: 2,
    cookTime: 5,
    imageUrl: 'https://images.unsplash.com/photo-1604977042946-1eecc30f269e?w=800',
    tags: '中餐,凉菜,快手,素食',
    ingredients: JSON.stringify([
      { name: '黄瓜', amount: 2, unit: '根' },
      { name: '蒜', amount: 3, unit: '瓣' },
      { name: '醋', amount: 2, unit: '勺' },
      { name: '生抽', amount: 1, unit: '勺' },
      { name: '香油', amount: 1, unit: '勺' },
      { name: '辣椒油', amount: 1, unit: '勺' },
      { name: '盐', amount: 0.5, unit: '茶勺' },
    ]),
    steps: JSON.stringify([
      '黄瓜拍碎切段',
      '蒜切末',
      '黄瓜加盐腌制5分钟',
      '倒掉多余水分',
      '加蒜末、醋、生抽、香油、辣椒油',
      '拌匀即可',
    ]),
    source: 'seed',
  },
  {
    title: '可乐鸡翅',
    description: '甜中带咸，色泽诱人，孩子最爱',
    servings: 3,
    cookTime: 30,
    imageUrl: 'https://images.unsplash.com/photo-1527477396000-e27163b481c2?w=800',
    tags: '中餐,家常,快手,晚餐',
    ingredients: JSON.stringify([
      { name: '鸡翅', amount: 10, unit: '个' },
      { name: '可乐', amount: 500, unit: 'ml' },
      { name: '生抽', amount: 2, unit: '勺' },
      { name: '老抽', amount: 1, unit: '勺' },
      { name: '姜片', amount: 3, unit: '片' },
      { name: '料酒', amount: 1, unit: '勺' },
      { name: '盐', amount: 0.5, unit: '茶勺' },
    ]),
    steps: JSON.stringify([
      '鸡翅洗净划两刀',
      '冷水下锅焯水去血沫',
      '热油煎鸡翅至两面金黄',
      '加姜片、料酒、生抽、老抽翻炒',
      '倒入可乐没过鸡翅',
      '大火烧开转中火煮20分钟',
      '大火收汁即可',
    ]),
    source: 'seed',
  },
  // 西餐/异国料理 - 10道
  {
    title: '意大利肉酱面',
    description: '经典意式美食，肉酱浓郁，面条Q弹',
    servings: 2,
    cookTime: 35,
    imageUrl: 'https://images.unsplash.com/photo-1621996346565-e3dbc646d9a9?w=800',
    tags: '西餐,意大利,主食,晚餐',
    ingredients: JSON.stringify([
      { name: '意大利面', amount: 200, unit: 'g' },
      { name: '牛肉末', amount: 200, unit: 'g' },
      { name: '番茄酱', amount: 150, unit: 'g' },
      { name: '洋葱', amount: 1, unit: '个' },
      { name: '蒜', amount: 3, unit: '瓣' },
      { name: '橄榄油', amount: 2, unit: '勺' },
      { name: '罗勒', amount: 5, unit: 'g' },
      { name: '盐', amount: 1, unit: '茶勺' },
    ]),
    steps: JSON.stringify([
      '煮意大利面至8成熟',
      '洋葱、蒜切末',
      '橄榄油炒香洋葱和蒜',
      '加牛肉末炒至变色',
      '加番茄酱煮15分钟',
      '加盐和罗勒调味',
      '拌入煮好的面条即可',
    ]),
    source: 'seed',
  },
  {
    title: '凯撒沙拉',
    description: '清爽健康，酱汁浓郁，营养均衡',
    servings: 2,
    cookTime: 15,
    imageUrl: 'https://images.unsplash.com/photo-1546793665-c74683f339c1?w=800',
    tags: '西餐,沙拉,健康,午餐',
    ingredients: JSON.stringify([
      { name: '罗马生菜', amount: 200, unit: 'g' },
      { name: '鸡胸肉', amount: 150, unit: 'g' },
      { name: '面包丁', amount: 50, unit: 'g' },
      { name: '帕玛森芝士', amount: 30, unit: 'g' },
      { name: '凯撒酱', amount: 50, unit: 'ml' },
      { name: '橄榄油', amount: 1, unit: '勺' },
      { name: '黑胡椒', amount: 1, unit: '茶勺' },
    ]),
    steps: JSON.stringify([
      '生菜洗净撕成小块',
      '鸡胸肉煎熟切片',
      '面包丁烤至金黄',
      '生菜装盘',
      '放上鸡肉和面包丁',
      '淋凯撒酱',
      '撒芝士碎和黑胡椒',
    ]),
    source: 'seed',
  },
  {
    title: '火腿芝士三明治',
    description: '快手早餐，营养丰富，方便携带',
    servings: 1,
    cookTime: 10,
    imageUrl: 'https://images.unsplash.com/photo-1528735602780-2552fd46c7af?w=800',
    tags: '西餐,早餐,快手,主食',
    ingredients: JSON.stringify([
      { name: '吐司', amount: 2, unit: '片' },
      { name: '火腿', amount: 2, unit: '片' },
      { name: '芝士片', amount: 2, unit: '片' },
      { name: '生菜', amount: 2, unit: '片' },
      { name: '番茄', amount: 2, unit: '片' },
      { name: '黄油', amount: 10, unit: 'g' },
      { name: '沙拉酱', amount: 1, unit: '勺' },
    ]),
    steps: JSON.stringify([
      '吐司涂黄油',
      '平底锅煎至两面金黄',
      '一片吐司依次放生菜、番茄、火腿、芝士',
      '淋沙拉酱',
      '盖上另一片吐司',
      '对角切开即可',
    ]),
    source: 'seed',
  },
  {
    title: '煎牛排',
    description: '外焦里嫩，肉质鲜美，西餐经典',
    servings: 2,
    cookTime: 20,
    imageUrl: 'https://images.unsplash.com/photo-1600891964092-4316c288032e?w=800',
    tags: '西餐,主菜,晚餐,高蛋白',
    ingredients: JSON.stringify([
      { name: '牛排', amount: 400, unit: 'g' },
      { name: '黄油', amount: 30, unit: 'g' },
      { name: '大蒜', amount: 3, unit: '瓣' },
      { name: '迷迭香', amount: 2, unit: '枝' },
      { name: '黑胡椒', amount: 1, unit: '茶勺' },
      { name: '盐', amount: 1, unit: '茶勺' },
    ]),
    steps: JSON.stringify([
      '牛排提前30分钟回温',
      '两面撒盐和黑胡椒',
      '平底锅大火烧热',
      '牛排下锅煎2分钟不动',
      '翻面再煎2分钟',
      '加黄油、蒜、迷迭香',
      '用勺子浇油在牛排上',
      '静置5分钟切片',
    ]),
    source: 'seed',
  },
  {
    title: '玛格丽特披萨',
    description: '意式经典，番茄芝士完美融合',
    servings: 2,
    cookTime: 25,
    imageUrl: 'https://images.unsplash.com/photo-1574071318508-1cdbab80d002?w=800',
    tags: '西餐,意大利,主食,晚餐',
    ingredients: JSON.stringify([
      { name: '披萨饼底', amount: 1, unit: '个' },
      { name: '番茄酱', amount: 100, unit: 'g' },
      { name: '马苏里拉芝士', amount: 150, unit: 'g' },
      { name: '番茄', amount: 1, unit: '个' },
      { name: '罗勒叶', amount: 10, unit: 'g' },
      { name: '橄榄油', amount: 1, unit: '勺' },
      { name: '盐', amount: 0.5, unit: '茶勺' },
    ]),
    steps: JSON.stringify([
      '饼底刷番茄酱',
      '铺上芝士',
      '放番茄片',
      '撒盐',
      '烤箱200度预热',
      '烤15分钟至芝士融化',
      '出炉撒罗勒叶，淋橄榄油',
    ]),
    source: 'seed',
  },
  {
    title: '煎蛋早餐',
    description: '简单营养，快速补充能量',
    servings: 1,
    cookTime: 10,
    imageUrl: 'https://images.unsplash.com/photo-1525351484163-7529414344d8?w=800',
    tags: '西餐,早餐,快手,高蛋白',
    ingredients: JSON.stringify([
      { name: '鸡蛋', amount: 2, unit: '个' },
      { name: '培根', amount: 3, unit: '片' },
      { name: '吐司', amount: 2, unit: '片' },
      { name: '番茄', amount: 1, unit: '个' },
      { name: '黄油', amount: 10, unit: 'g' },
      { name: '盐', amount: 0.5, unit: '茶勺' },
      { name: '黑胡椒', amount: 0.5, unit: '茶勺' },
    ]),
    steps: JSON.stringify([
      '平底锅煎培根至酥脆',
      '用培根油煎鸡蛋',
      '撒盐和黑胡椒',
      '吐司烤至金黄',
      '番茄切片',
      '装盘即可',
    ]),
    source: 'seed',
  },
  {
    title: '燕麦水果碗',
    description: '健康低脂，饱腹感强，营养均衡',
    servings: 1,
    cookTime: 10,
    imageUrl: 'https://images.unsplash.com/photo-1590301157890-4810ed352733?w=800',
    tags: '西餐,早餐,健康,素食',
    ingredients: JSON.stringify([
      { name: '燕麦片', amount: 50, unit: 'g' },
      { name: '牛奶', amount: 200, unit: 'ml' },
      { name: '香蕉', amount: 1, unit: '根' },
      { name: '蓝莓', amount: 50, unit: 'g' },
      { name: '蜂蜜', amount: 1, unit: '勺' },
      { name: '坚果', amount: 20, unit: 'g' },
    ]),
    steps: JSON.stringify([
      '燕麦加牛奶煮5分钟',
      '香蕉切片',
      '燕麦盛入碗中',
      '放上香蕉和蓝莓',
      '撒坚果',
      '淋蜂蜜即可',
    ]),
    source: 'seed',
  },
  {
    title: '日式咖喱鸡饭',
    description: '香浓可口，米饭杀手，简单易做',
    servings: 3,
    cookTime: 40,
    imageUrl: 'https://images.unsplash.com/photo-1585937421612-70e008356f33?w=800',
    tags: '异国料理,日式,主食,晚餐',
    ingredients: JSON.stringify([
      { name: '鸡腿肉', amount: 300, unit: 'g' },
      { name: '土豆', amount: 2, unit: '个' },
      { name: '胡萝卜', amount: 1, unit: '根' },
      { name: '洋葱', amount: 1, unit: '个' },
      { name: '咖喱块', amount: 100, unit: 'g' },
      { name: '米饭', amount: 600, unit: 'g' },
    ]),
    steps: JSON.stringify([
      '鸡肉、土豆、胡萝卜、洋葱切块',
      '热油炒香洋葱',
      '加鸡肉炒至变色',
      '加土豆和胡萝卜翻炒',
      '加水没过食材，煮20分钟',
      '加咖喱块煮至浓稠',
      '浇在米饭上即可',
    ]),
    source: 'seed',
  },
  {
    title: '越南河粉',
    description: '清爽鲜美，汤头浓郁，东南亚风味',
    servings: 2,
    cookTime: 30,
    imageUrl: 'https://images.unsplash.com/photo-1582878826629-29b7ad1cdc43?w=800',
    tags: '异国料理,越南,主食,午餐',
    ingredients: JSON.stringify([
      { name: '河粉', amount: 300, unit: 'g' },
      { name: '牛肉片', amount: 200, unit: 'g' },
      { name: '豆芽', amount: 100, unit: 'g' },
      { name: '香菜', amount: 20, unit: 'g' },
      { name: '洋葱', amount: 0.5, unit: '个' },
      { name: '柠檬', amount: 1, unit: '个' },
      { name: '鱼露', amount: 2, unit: '勺' },
      { name: '牛骨汤', amount: 800, unit: 'ml' },
    ]),
    steps: JSON.stringify([
      '牛骨汤加鱼露煮开',
      '河粉煮熟',
      '洋葱切丝',
      '河粉装碗',
      '放牛肉片、豆芽、洋葱',
      '浇热汤',
      '撒香菜，挤柠檬汁',
    ]),
    source: 'seed',
  },
  {
    title: '泰式炒河粉',
    description: '酸甜辣咸，口味丰富，泰国国民美食',
    servings: 2,
    cookTime: 20,
    imageUrl: 'https://images.unsplash.com/photo-1559314809-0d155014e29e?w=800',
    tags: '异国料理,泰式,主食,晚餐',
    ingredients: JSON.stringify([
      { name: '河粉', amount: 300, unit: 'g' },
      { name: '虾', amount: 150, unit: 'g' },
      { name: '鸡蛋', amount: 2, unit: '个' },
      { name: '豆芽', amount: 100, unit: 'g' },
      { name: '韭菜', amount: 50, unit: 'g' },
      { name: '花生碎', amount: 30, unit: 'g' },
      { name: '鱼露', amount: 2, unit: '勺' },
      { name: '罗望子酱', amount: 1, unit: '勺' },
      { name: '糖', amount: 1, unit: '勺' },
    ]),
    steps: JSON.stringify([
      '河粉泡软',
      '热油炒虾至变色盛出',
      '炒鸡蛋至凝固',
      '下河粉翻炒',
      '加鱼露、罗望子酱、糖调味',
      '加虾、豆芽、韭菜翻炒',
      '撒花生碎出锅',
    ]),
    source: 'seed',
  },
];

async function main() {
  console.log('开始数据填充...');

  // 创建测试用户
  const hashedPassword = await bcrypt.hash('password123', 10);
  const user = await prisma.user.upsert({
    where: { phone: '13800138000' },
    update: {},
    create: {
      phone: '13800138000',
      password: hashedPassword,
      name: '测试用户',
      familySize: 2,
    },
  });

  console.log(`用户创建成功: ${user.name} (${user.phone})`);

  // 删除该用户的旧食谱
  await prisma.recipe.deleteMany({ where: { userId: user.id } });

  // 创建食谱
  await prisma.recipe.createMany({
    data: recipes.map(r => ({ ...r, userId: user.id })),
  });

  console.log(`成功创建 ${recipes.length} 道食谱`);
  console.log('数据填充完成!');
}

main()
  .catch((e) => {
    console.error('数据填充失败:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });

